import os
import sys
def clear():                                                                                                                                           # defines a really useful thing that clears the whole terminal screen
    os.system('cls' if os.name == 'nt' else 'clear')                                                                                                   # defines it for linux and windows for better compatibility
                                                                                                                                                       # free space
                                                                                                                                                       # more of it
clear()                                                                                                                                                # clears the screen before starting
print("Calc file recode!")                                                                                                                             # tells you that i recoded my calc file (my first actual mini-project!)
listofots = ["+","-","x","√","/","^","1","2","3","4","5","6","addition","subtraction","multiplication","division","exponent","square root"]            # list that will be used later listing all types of operation i work with on this program
import time                                                                                                                                            # imports time for better user experience
time.sleep(3.5)                                                                                                                                        # waits a little bit for you to be able to read allat text (jk idk why its that long)
while True:                                                                                                                                            # starts the whole loop thing for user to be able to make a lot of calculations on one long session (tho idk who the f*** is spending that much time on my stupid calc)
 clear()                                                                                                                                               # clears the entire screen for start of loop to look cool
 wfn = 0                                                                                                                                               # first number placeholder  
 wot = "+"                                                                                                                                             # define variables
 wsn = 0                                                                                                                                               # yeah thats what it does, duh
 YUN = False                                                                                                                                           # global flag for exponent with decimal check
 # | ################################# -  FIRST NUMBER INPUT  - ################################# | #                                                  | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # |
 while True:                                                                                                                                           # starts loop so if user mistypes/there´s an error they can try again over and over and over instead of getting an error
  fn = input("Input first number  > ")                                                                                                                 # inputs user for first number
  try:                                                                                                                                                 # this whole part is reused like three times and it defines what the program works with at the end, checks if the number is a decimal or not and gives it a worthy number instead of like 4.0 or if theres an errror and shit and it is cool
   wfn = int(fn)                                                                                                                                       # see? tries to set the first number not to have a comma if it isnt a decimal
   fndon = "nd"                                                                                                                                        # over here it sends something that we will use later in case the user uses a decimal and tries to use it along with an exponency (i think thats its name) to like block that case so we dont get errors
   break                                                                                                                                               # in case it works it lets the user proceed
  except ValueError:                                                                                                                                   # but, in case it doesnt it proceeds with the other option
   try:                                                                                                                                                # this tries to set it as a float and send the same signal as the first one (saying "hey! the first number is a decimal!")
    wfn = float(fn)                                                                                                                                    # tries to set the number to a float
    fndon = "d"                                                                                                                                        # sends the signal
    break                                                                                                                                              # in case it works, it lets the user proceed with the calculation
   except ValueError:                                                                                                                                  # if none of these work, it sends the user back to the input
    print("Error, please enter a valid number!")                                                                                                       # tells the user the fact that their input isnt a number
 # | ################################# -  OPERATION TYPE INPUT  - ################################# | #                                                | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # |
 while True:                                                                                                                                           # starts loop so if user mistypes/there´s an error they can try again over and over and over instead of getting an error
  print(" ")                                                                                                                                           # makes space
  print("First number =",fn," Operation type = ?  Second number = ?")                                                                                  # tells the user what their first number was so that you have a point of reference
  ot = input("Enter operation type (type ? to see all operation types)  > ")                                                                           # inputs user for what type of operation they wanna do and informs them that if they type ? they can see all types supported
  if ot == "?":                                                                                                                                        # in case that user types ? shows them all operation types
     clear()                                                                                                                                           # clears screen for space
     print("_____________________________________________________________________")                                                                    # top of the informative thing
     print("|                                                                   |")                                                                    # free space for visual commodity
     print("| Operation types:                                                  |")                                                                    # text
     print("|  (1) Addition(+)     (2) Subtraction(-)    (3) Multiplication(x)  |")                                                                    # mentions three of the six operation types
     print("|  (4) Division(/)     (5) Exponent(^)       (6) Root(√)            |")                                                                    # mentions the rest of the operation types
     print("|                                                                   |")                                                                    # free space for visual commodity
     print(" ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅ ̅")                                                                      # end of the informative thing
     print(" ")                                                                                                                                        # free space
     print(" ")                                                                                                                                        # more free space
     continue                                                                                                                                          # continues (what did you expect)
                                                                                                                                                       # free space
  if ot.lower() not in listofots:                                                                                                                      # checks a list i made for all possible responses for the input and if the response is not on there, repeat
     print("operation not recognized")                                                                                                                 # tells the user that they´re operation isn´t on my list
     continue                                                                                                                                          # ...
                                                                                                                                                       # free space
  if fndon == "d" and ot == "5" or fndon == "d" and ot.lower() == "exponent" or fndon == "d" and ot.lower() == "^":                                    # long ass thing but basically uses the previous signal to check if the first number was a decimal and the operation type is exponential type  and if its true then it says nuh uh and makes you retype it
     print("Operation type isnt possible as you have set a decimal as your first number, and you cant use exponentials along with decimals")           # explains what i just said to you but in text
     time.sleep(3)                                                                                                                                     # gives you time to read
     continue                                                                                                                                          # dude dont read these ones ok?
                                                                                                                                                       # free space
  break                                                                                                                                                # lets the user continue if all passing conditions are met
 # | ################################# -  SECOND NUMBER INPUT  - ################################# | #                                                 | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # |
 while True:                                                                                                                                           # same drill as the first number input
  print(" ")                                                                                                                                           # not even gonna comment on mosta these ones with that much detail as its mostly reused code from the 1st one
  print("First number =",fn," Operation type =",ot," Second number = ?")                                                                               # tells the user previous choices
  sn = input("Input Second Number  > ")                                                                                                                # inputs for 2nd number
                                                                                                                                                       # free space
  try:                                                                                                                                                 # tries to get if decimal or not
   wsn = int(sn)                                                                                                                                       # checks if it is an integer
   sndon = "nd"                                                                                                                                        # if it is makes signal but v2 for it not to be a decimal
   break                                                                                                                                               # if it works, lets user through to see their result
  except ValueError:                                                                                                                                   # in case it doesnt then it does the same then the first one but with a twist
   try:                                                                                                                                                # tries to check if it is or not an decimal
    wsn = float(sn)                                                                                                                                    # checks that
    sndon = "d"                                                                                                                                        # if it is it sends the signal
    if ot == "5" or ot.lower() == "exponent" or ot == "^":                                                                                             # if the operation type is exponential and the second number is a decimal then tells the user that it doesnt work and makes them reinupt the 2nd number
      YUN = True                                                                                                                                       # sets a value to true that is later used so that user needs to retype
      print("Operation type isnt possible as you have set a decimal as your second number, and you cant use exponentials along with decimals")         # explains the incompatibility thing to the user
    elif YUN == False:                                                                                                                                 # if the value doesnt change it lets the user through to see their result
      break                                                                                                                                            # lets them through
   except ValueError:                                                                                                                                  # in case non of those work it tells the user that they inputted a wrong number
    print("Error, please enter a valid number!")                                                                                                       # tells the user they number dont work
 import random                                                                                                                                         # imports random as a module for generation of completely innecesary cutscene
 time.sleep(0.6767)                                                                                                                                    # waits (SIIIXXXXXXX SEEVEEEEENNNNNNN)(holy fuck what am i doing with my life)(/j)
 clear()                                                                                                                                               # clears for space
 for _ in range(random.randint(6,9)):                                                                                                                  # basically this makes a number from 6 to 9 and makes the user wait through a wait that number of times
     for dots in [".", "..", "..."]:                                                                                                                   # defines those three as the three states for the dots in the animation
         print(f"Calculating{dots}")                                                                                                                   # this is the animation that plays with a text (text part + dots part on this line)
         time.sleep(0.15)                                                                                                                              # waits .15 secs to change frame 1 to frame 2 and so it goes
         clear()                                                                                                                                       # clears the screen for the old frame to dissapear and show the new one till the random time of dots is over
                                                                                                                                                       # free space
 # | ################################# -  RESLULT CALCULATIONS  - ################################# | #                                                | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # | # |
 if ot.lower() == "+" or ot.lower() == "addition" or ot == "1":                                                                                        # in case the operation type was a sum then adds both numbers up and gets the result
   result = wfn + wsn                                                                                                                                  # does the math and makes the result identify as the variable "result"
   rot = "+"                                                                                                                                           # sends a signal for convenience at the end
 elif ot.lower() == "-" or ot.lower() == "subtraction" or ot == "2":                                                                                   # in case the operation type was a subtraction then subtracts a number from the other and gets the result
   result = wfn - wsn                                                                                                                                  # does the math and makes the result identify as the variable "result"
   rot = "-"                                                                                                                                           # sends a signal for convenience at the end
 elif ot.lower() == "x" or ot.lower() == "multiplication" or ot == "3":                                                                                # in case the operation type was a multiplication then multiplies the numbers inbetween each other and gets the result
   result = wfn * wsn                                                                                                                                  # does the math and makes the result identify as the variable "result"
   rot = "x"                                                                                                                                           # sends a signal for convenience at the end
 elif ot.lower() == "/" or ot.lower() == "division" or ot == "4":                                                                                      # in case the operation type was a division then divides a number from the other and gets the result
   result = wfn / wsn                                                                                                                                  # does the math and makes the result identify as the variable "result"
   rot = "/"                                                                                                                                           # sends a signal for convenience at the end
 elif ot.lower() == "^" or ot.lower() == "exponent" or ot == "5":                                                                                      # in case the operation type was an exponent then does a number elevated to the other and gets the result
   result = wfn ** wsn                                                                                                                                 # does the math and makes the result identify as the variable "result"
   rot = "^"                                                                                                                                           # sends a signal for convenience at the end
 elif ot.lower() == "√" or ot.lower() == "square root" or ot == "6":                                                                                   # in case the operation type was an square root then does the square root of a number by the other (i dont know how tf to type this in)
   result = wfn // wsn                                                                                                                                 # does the math and makes the result identify as the variable "result"
   rot = "√"                                                                                                                                           # sends a signal for convenience at the end
 try:                                                                                                                                                  # tries to get the result as an integer or a decimal reusing my famous piece of code that i pasted like two times already
  wrt = int(result)                                                                                                                                    # yall should know how it works as of now
  pass                                                                                                                                                 # cuz yknow i explained it a lot and got tired of explaining it
 except ValueError:                                                                                                                                    # so i am not gonna type nothing inportant on here
    wrt = float(result)                                                                                                                                # cuz no one should be looking at here rn
    pass                                                                                                                                               # should just be scrolling by these lines
 time.sleep(0.6767)                                                                                                                                    # waits SIXX SEVENNNN seconds b4 showing the reuslt
 print("Your result is:",wrt)                                                                                                                          # displays the result
 print("(",fn,rot,sn,"=",wrt,")")                                                                                                                      # displays how the result was done using the signals previously sended
 print(" ")                                                                                                                                            # makes space for visual commoddity
 while True:                                                                                                                                           # asks the user if they wanna keep doing math and basically loops back
  redo = input("Want to do another calculation? (Y/N) > ").lower()                                                                                     # asks them the thing
  if redo == "y":                                                                                                                                      # if they want to they get looped (aura monster subaru edit appears)
    print("Ok! Restarting program...")                                                                                                                 # tells the user that its restarting
    time.sleep(3.67)                                                                                                                                   # delays the time for restart to enable the legibility of the previous message
    break                                                                                                                                              # loops
  elif redo == "n":                                                                                                                                    # if they dont they get asked a sure?
    while True:                                                                                                                                        # loop in case of mistypes
     recheck = input("Are you sure? Inputting yes will close the program (Y/N) > ").lower()                                                            # if user types yes they close the program in the other case they can do more math
     if recheck == "y":                                                                                                                                # if yes the program exits
       sys.exit(0)                                                                                                                                     # code to exit without errors
     elif recheck == "n":                                                                                                                              # but if they arent sure
       print("ok")                                                                                                                                     # they loop to do more math
       break                                                                                                                                           # breaks the thing
     else:                                                                                                                                             # in case none of these options are selected there is a error shown and the user is prompted again
       print("Not a proper response, please input again")                                                                                              # tells em the error thingy
       print(" ")                                                                                                                                      # space for visual commodity
  else:                                                                                                                                                # 2nd error part for the first question asked
    print("Not a proper response, please input again")                                                                                                 # tells em the error thingy
    print(" ")                                                                                                                                         # space for visual commodity
                                                                                                                                                        # congratulations coming straight from me: ty for reading ts, it took me like 1.3 hours to make (just the comments part) i appreciate you taking the time to read allthis  -dante